### PR TITLE
Fix gss_localname

### PR DESCRIPTION
**Pull request by simo5**
Commit 9c555e2a42653153c0f0159446b90a26c14e9465 regressed this interface.

This PR fixes it and adds a test to make sure it stays fixed.

We have to use curl because apparently request_gssapi is not always doing that.

### CODE REVIEW

**Comment by simo5** [comment]
@alejandro-perez PTAL (your patch cause regression :)

**Comment by mattwoodyard** [comment]
Built it and ran it in my dev environment, works.

**Comment by alejandro-perez** [comment]
Will take a look tomorrow, thanks for the headsup

**Comment by simo5** [comment]
@frozencemetery I fixed the .travis.sh issue, I kept the commits separate so you can see that the test fail for SPNEGO only if you revert just the fix commit

**Comment by alejandro-perez** [comment]
FWIW, it works fine with GSS-EAP, which was the motivation for making the change in the first place.

**Pull request merged**
